/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TripsRouteImport } from './routes/trips'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as NairobiToIsioloRouteImport } from './routes/nairobi-to-isiolo'
import { Route as MyBookingsRouteImport } from './routes/my-bookings'
import { Route as IsioloToNairobiRouteImport } from './routes/isiolo-to-nairobi'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DriverIndexRouteImport } from './routes/driver.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as DriverSignupRouteImport } from './routes/driver.signup'
import { Route as DriverLoginRouteImport } from './routes/driver.login'
import { Route as DriverDriverIdRouteImport } from './routes/driver.$driverId'
import { Route as BookingBookingIdRouteImport } from './routes/booking.$bookingId'
import { Route as BookTripIdRouteImport } from './routes/book.$tripId'
import { Route as AdminLoginRouteImport } from './routes/admin.login'

const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const NairobiToIsioloRoute = NairobiToIsioloRouteImport.update({
  id: '/nairobi-to-isiolo',
  path: '/nairobi-to-isiolo',
  getParentRoute: () => rootRouteImport,
} as any)
const MyBookingsRoute = MyBookingsRouteImport.update({
  id: '/my-bookings',
  path: '/my-bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const IsioloToNairobiRoute = IsioloToNairobiRouteImport.update({
  id: '/isiolo-to-nairobi',
  path: '/isiolo-to-nairobi',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverIndexRoute = DriverIndexRouteImport.update({
  id: '/driver/',
  path: '/driver/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverSignupRoute = DriverSignupRouteImport.update({
  id: '/driver/signup',
  path: '/driver/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverLoginRoute = DriverLoginRouteImport.update({
  id: '/driver/login',
  path: '/driver/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverDriverIdRoute = DriverDriverIdRouteImport.update({
  id: '/driver/$driverId',
  path: '/driver/$driverId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingBookingIdRoute = BookingBookingIdRouteImport.update({
  id: '/booking/$bookingId',
  path: '/booking/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookTripIdRoute = BookTripIdRouteImport.update({
  id: '/book/$tripId',
  path: '/book/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/isiolo-to-nairobi': typeof IsioloToNairobiRoute
  '/my-bookings': typeof MyBookingsRoute
  '/nairobi-to-isiolo': typeof NairobiToIsioloRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trips': typeof TripsRoute
  '/admin/login': typeof AdminLoginRoute
  '/book/$tripId': typeof BookTripIdRoute
  '/booking/$bookingId': typeof BookingBookingIdRoute
  '/driver/$driverId': typeof DriverDriverIdRoute
  '/driver/login': typeof DriverLoginRoute
  '/driver/signup': typeof DriverSignupRoute
  '/admin/': typeof AdminIndexRoute
  '/driver/': typeof DriverIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/isiolo-to-nairobi': typeof IsioloToNairobiRoute
  '/my-bookings': typeof MyBookingsRoute
  '/nairobi-to-isiolo': typeof NairobiToIsioloRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trips': typeof TripsRoute
  '/admin/login': typeof AdminLoginRoute
  '/book/$tripId': typeof BookTripIdRoute
  '/booking/$bookingId': typeof BookingBookingIdRoute
  '/driver/$driverId': typeof DriverDriverIdRoute
  '/driver/login': typeof DriverLoginRoute
  '/driver/signup': typeof DriverSignupRoute
  '/admin': typeof AdminIndexRoute
  '/driver': typeof DriverIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/isiolo-to-nairobi': typeof IsioloToNairobiRoute
  '/my-bookings': typeof MyBookingsRoute
  '/nairobi-to-isiolo': typeof NairobiToIsioloRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trips': typeof TripsRoute
  '/admin/login': typeof AdminLoginRoute
  '/book/$tripId': typeof BookTripIdRoute
  '/booking/$bookingId': typeof BookingBookingIdRoute
  '/driver/$driverId': typeof DriverDriverIdRoute
  '/driver/login': typeof DriverLoginRoute
  '/driver/signup': typeof DriverSignupRoute
  '/admin/': typeof AdminIndexRoute
  '/driver/': typeof DriverIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/history'
    | '/isiolo-to-nairobi'
    | '/my-bookings'
    | '/nairobi-to-isiolo'
    | '/reset-password'
    | '/sitemap.xml'
    | '/trips'
    | '/admin/login'
    | '/book/$tripId'
    | '/booking/$bookingId'
    | '/driver/$driverId'
    | '/driver/login'
    | '/driver/signup'
    | '/admin/'
    | '/driver/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/history'
    | '/isiolo-to-nairobi'
    | '/my-bookings'
    | '/nairobi-to-isiolo'
    | '/reset-password'
    | '/sitemap.xml'
    | '/trips'
    | '/admin/login'
    | '/book/$tripId'
    | '/booking/$bookingId'
    | '/driver/$driverId'
    | '/driver/login'
    | '/driver/signup'
    | '/admin'
    | '/driver'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/history'
    | '/isiolo-to-nairobi'
    | '/my-bookings'
    | '/nairobi-to-isiolo'
    | '/reset-password'
    | '/sitemap.xml'
    | '/trips'
    | '/admin/login'
    | '/book/$tripId'
    | '/booking/$bookingId'
    | '/driver/$driverId'
    | '/driver/login'
    | '/driver/signup'
    | '/admin/'
    | '/driver/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HistoryRoute: typeof HistoryRoute
  IsioloToNairobiRoute: typeof IsioloToNairobiRoute
  MyBookingsRoute: typeof MyBookingsRoute
  NairobiToIsioloRoute: typeof NairobiToIsioloRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TripsRoute: typeof TripsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  BookTripIdRoute: typeof BookTripIdRoute
  BookingBookingIdRoute: typeof BookingBookingIdRoute
  DriverDriverIdRoute: typeof DriverDriverIdRoute
  DriverLoginRoute: typeof DriverLoginRoute
  DriverSignupRoute: typeof DriverSignupRoute
  AdminIndexRoute: typeof AdminIndexRoute
  DriverIndexRoute: typeof DriverIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nairobi-to-isiolo': {
      id: '/nairobi-to-isiolo'
      path: '/nairobi-to-isiolo'
      fullPath: '/nairobi-to-isiolo'
      preLoaderRoute: typeof NairobiToIsioloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-bookings': {
      id: '/my-bookings'
      path: '/my-bookings'
      fullPath: '/my-bookings'
      preLoaderRoute: typeof MyBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/isiolo-to-nairobi': {
      id: '/isiolo-to-nairobi'
      path: '/isiolo-to-nairobi'
      fullPath: '/isiolo-to-nairobi'
      preLoaderRoute: typeof IsioloToNairobiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/': {
      id: '/driver/'
      path: '/driver'
      fullPath: '/driver/'
      preLoaderRoute: typeof DriverIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/signup': {
      id: '/driver/signup'
      path: '/driver/signup'
      fullPath: '/driver/signup'
      preLoaderRoute: typeof DriverSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/login': {
      id: '/driver/login'
      path: '/driver/login'
      fullPath: '/driver/login'
      preLoaderRoute: typeof DriverLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/$driverId': {
      id: '/driver/$driverId'
      path: '/driver/$driverId'
      fullPath: '/driver/$driverId'
      preLoaderRoute: typeof DriverDriverIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$bookingId': {
      id: '/booking/$bookingId'
      path: '/booking/$bookingId'
      fullPath: '/booking/$bookingId'
      preLoaderRoute: typeof BookingBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$tripId': {
      id: '/book/$tripId'
      path: '/book/$tripId'
      fullPath: '/book/$tripId'
      preLoaderRoute: typeof BookTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HistoryRoute: HistoryRoute,
  IsioloToNairobiRoute: IsioloToNairobiRoute,
  MyBookingsRoute: MyBookingsRoute,
  NairobiToIsioloRoute: NairobiToIsioloRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TripsRoute: TripsRoute,
  AdminLoginRoute: AdminLoginRoute,
  BookTripIdRoute: BookTripIdRoute,
  BookingBookingIdRoute: BookingBookingIdRoute,
  DriverDriverIdRoute: DriverDriverIdRoute,
  DriverLoginRoute: DriverLoginRoute,
  DriverSignupRoute: DriverSignupRoute,
  AdminIndexRoute: AdminIndexRoute,
  DriverIndexRoute: DriverIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
